CREATE SCHEMA "ROOTS";

CREATE TABLE ROOTS.IDENTITIESS
    (ID INT NOT NULL GENERATED ALWAYS AS IDENTITY
    CONSTRAINT IDENTITY_PK PRIMARY KEY, 
    
    DISPLAY_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    UID VARCHAR(255)
    
    );
    select * from IDENTITIESS;
    
    CREATE TABLE ROOTS.LOGIN
    (ID INT NOT NULL GENERATED ALWAYS AS IDENTITY
    CONSTRAINT LOGIN_PK PRIMARY KEY, 
    
    USER_NAME VARCHAR(255),
    PWD VARCHAR(255)
    
    );
    
    INSERT INTO LOGIN(USER_NAME, PWD) VALUES ('naveen', '123');
    select * from LOGIN;
    
    CREATE SCHEMA "USER";
    
    